name: build

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/main.yml'
      - '.github/workflows/buildx.yml'
      - '.github/workflows/buildx-cuda.yml'
      - '.dockerignore'
      - 'Dockerfile'
      - 'Dockerfile.cuda'
      - 'manage.sh'
      - 'run.sh'

jobs:
  shellcheck:
    if: github.repository_owner == 'hwdsl2'
    uses: ./.github/workflows/shellcheck.yml

  ollama_test:
    needs: [shellcheck]
    uses: ./.github/workflows/ollama_test.yml

  buildx:
    needs: [shellcheck, ollama_test]
    uses: ./.github/workflows/buildx.yml
    secrets:
      CACHE_NAME: ${{ secrets.CACHE_NAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      QUAY_USER: ${{ secrets.QUAY_USER }}
      QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}
      BUILD_ONLY: ${{ secrets.BUILD_ONLY }}

  buildx-cuda:
    needs: [shellcheck, ollama_test]
    uses: ./.github/workflows/buildx-cuda.yml
    secrets:
      CACHE_NAME: ${{ secrets.CACHE_NAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      QUAY_USER: ${{ secrets.QUAY_USER }}
      QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}
      BUILD_ONLY: ${{ secrets.BUILD_ONLY }}